[package]
name = "apid"
version = "0.1.1"
edition = "2021"
authors = ["RanolP <public.ranolp@gmail.com"]
repository = "https://github.com/bot-any/apid"
license = "MIT"
description = "Collection of type definitions from several APIs"
readme = "../README.md"

[dependencies]
